export { default as Header } from "./layout/Header"
export { default as Footer } from "./layout/Footer"

// elements
export { default as Hero } from "./elements/Hero"
export { default as WhatGain } from "./elements/WhatGain"
export { default as CallToAction } from "./elements/CallToAction"
export { default as Presentation } from "./elements/Presentation"
export { default as WatchDemo } from "./elements/WatchDemo"
export { default as MostViewed } from "./elements/MostViewed"
export { default as NewBlogs } from "./elements/NewBlogs"
export { default as HeroSection } from "./elements/HeroSection"
export { default as FormAuthCode } from "./elements/FormAuthCode"
export { default as Experts } from "./elements/Experts"
export { default as ContactForm } from "./elements/ContactForm"
export { default as FaqDetailed } from "./elements/FaqDetailed"
export { default as Newsletter } from "./elements/Newsletter"
export { default as WhyChooseUs } from "./elements/WhyChooseUs"
export { default as Features } from "./elements/Features"

export { default as CheckoutOne } from "./checkout/CheckoutOne"
export { default as CheckoutTwo } from "./checkout/CheckoutTwo"
export { default as CheckoutThree } from "./checkout/CheckoutThree"
export { default as CardCheckout } from "./checkout/Card"